[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm install -g serve && serve -s dist -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
